/* ============================================================
   FunEnglish Kids – Data (words, alphabet, vocabulary)
   ============================================================ */

// Alphabet data: letter → { word, emoji, color }
const ALPHABET = [
  { letter: 'A', word: 'Apple',    emoji: '🍎', color: '#ff6b6b' },
  { letter: 'B', word: 'Banana',   emoji: '🍌', color: '#fd9644' },
  { letter: 'C', word: 'Cat',      emoji: '🐱', color: '#feca57' },
  { letter: 'D', word: 'Dog',      emoji: '🐶', color: '#ff9ff3' },
  { letter: 'E', word: 'Elephant', emoji: '🐘', color: '#48dbfb' },
  { letter: 'F', word: 'Fish',     emoji: '🐟', color: '#ff6b6b' },
  { letter: 'G', word: 'Giraffe',  emoji: '🦒', color: '#ffd32a' },
  { letter: 'H', word: 'Horse',    emoji: '🐴', color: '#ff9f43' },
  { letter: 'I', word: 'Igloo',    emoji: '🏔️', color: '#a29bfe' },
  { letter: 'J', word: 'Jellyfish',emoji: '🪼', color: '#fd79a8' },
  { letter: 'K', word: 'Kite',     emoji: '🪁', color: '#6c5ce7' },
  { letter: 'L', word: 'Lion',     emoji: '🦁', color: '#f9ca24' },
  { letter: 'M', word: 'Monkey',   emoji: '🐵', color: '#f0932b' },
  { letter: 'N', word: 'Nest',     emoji: '🪺', color: '#6ab04c' },
  { letter: 'O', word: 'Octopus',  emoji: '🐙', color: '#e84393' },
  { letter: 'P', word: 'Penguin',  emoji: '🐧', color: '#30336b' },
  { letter: 'Q', word: 'Queen',    emoji: '👸', color: '#8e44ad' },
  { letter: 'R', word: 'Rabbit',   emoji: '🐰', color: '#ff6b6b' },
  { letter: 'S', word: 'Snake',    emoji: '🐍', color: '#2ecc71' },
  { letter: 'T', word: 'Tiger',    emoji: '🐯', color: '#e67e22' },
  { letter: 'U', word: 'Umbrella', emoji: '☂️', color: '#1abc9c' },
  { letter: 'V', word: 'Violin',   emoji: '🎻', color: '#8e44ad' },
  { letter: 'W', word: 'Whale',    emoji: '🐋', color: '#3498db' },
  { letter: 'X', word: 'X-ray',    emoji: '🩻', color: '#2c3e50' },
  { letter: 'Y', word: 'Yacht',    emoji: '⛵', color: '#16a085' },
  { letter: 'Z', word: 'Zebra',    emoji: '🦓', color: '#2c3e50' },
];

// Vocabulary categories
const VOCAB = {
  animals: [
    { emoji: '🐶', word: 'Dog',       phonetic: '/dɒɡ/' },
    { emoji: '🐱', word: 'Cat',       phonetic: '/kæt/' },
    { emoji: '🐸', word: 'Frog',      phonetic: '/frɒɡ/' },
    { emoji: '🐧', word: 'Penguin',   phonetic: '/ˈpeŋɡwɪn/' },
    { emoji: '🦁', word: 'Lion',      phonetic: '/ˈlaɪən/' },
    { emoji: '🐘', word: 'Elephant',  phonetic: '/ˈelɪfənt/' },
    { emoji: '🦊', word: 'Fox',       phonetic: '/fɒks/' },
    { emoji: '🐬', word: 'Dolphin',   phonetic: '/ˈdɒlfɪn/' },
    { emoji: '🐻', word: 'Bear',      phonetic: '/beə/' },
    { emoji: '🦒', word: 'Giraffe',   phonetic: '/dʒɪˈrɑːf/' },
    { emoji: '🐯', word: 'Tiger',     phonetic: '/ˈtaɪɡə/' },
    { emoji: '🐙', word: 'Octopus',   phonetic: '/ˈɒktəpəs/' },
  ],
  colors: [
    { emoji: '🔴', word: 'Red',       phonetic: '/red/' },
    { emoji: '🔵', word: 'Blue',      phonetic: '/bluː/' },
    { emoji: '🟡', word: 'Yellow',    phonetic: '/ˈjeloʊ/' },
    { emoji: '🟢', word: 'Green',     phonetic: '/ɡriːn/' },
    { emoji: '🟠', word: 'Orange',    phonetic: '/ˈɒrɪndʒ/' },
    { emoji: '🟣', word: 'Purple',    phonetic: '/ˈpɜːpəl/' },
    { emoji: '⚫', word: 'Black',     phonetic: '/blæk/' },
    { emoji: '⚪', word: 'White',     phonetic: '/waɪt/' },
    { emoji: '🩷', word: 'Pink',      phonetic: '/pɪŋk/' },
    { emoji: '🟤', word: 'Brown',     phonetic: '/braʊn/' },
    { emoji: '🩵', word: 'Cyan',      phonetic: '/ˈsaɪæn/' },
    { emoji: '🪸', word: 'Coral',     phonetic: '/ˈkɒrəl/' },
  ],
  numbers: [
    { emoji: '1️⃣', word: 'One',      phonetic: '/wʌn/' },
    { emoji: '2️⃣', word: 'Two',      phonetic: '/tuː/' },
    { emoji: '3️⃣', word: 'Three',    phonetic: '/θriː/' },
    { emoji: '4️⃣', word: 'Four',     phonetic: '/fɔː/' },
    { emoji: '5️⃣', word: 'Five',     phonetic: '/faɪv/' },
    { emoji: '6️⃣', word: 'Six',      phonetic: '/sɪks/' },
    { emoji: '7️⃣', word: 'Seven',    phonetic: '/ˈsevən/' },
    { emoji: '8️⃣', word: 'Eight',    phonetic: '/eɪt/' },
    { emoji: '9️⃣', word: 'Nine',     phonetic: '/naɪn/' },
    { emoji: '🔟', word: 'Ten',      phonetic: '/ten/' },
    { emoji: '💯', word: 'Hundred',  phonetic: '/ˈhʌndrəd/' },
    { emoji: '♾️', word: 'Infinity', phonetic: '/ɪnˈfɪnɪti/' },
  ],
  fruits: [
    { emoji: '🍎', word: 'Apple',     phonetic: '/ˈæpəl/' },
    { emoji: '🍌', word: 'Banana',    phonetic: '/bəˈnɑːnə/' },
    { emoji: '🍇', word: 'Grapes',    phonetic: '/ɡreɪps/' },
    { emoji: '🍓', word: 'Strawberry',phonetic: '/ˈstrɔːbəri/' },
    { emoji: '🍊', word: 'Orange',    phonetic: '/ˈɒrɪndʒ/' },
    { emoji: '🍋', word: 'Lemon',     phonetic: '/ˈlemən/' },
    { emoji: '🍑', word: 'Peach',     phonetic: '/piːtʃ/' },
    { emoji: '🥭', word: 'Mango',     phonetic: '/ˈmæŋɡoʊ/' },
    { emoji: '🍍', word: 'Pineapple', phonetic: '/ˈpaɪnæpəl/' },
    { emoji: '🍒', word: 'Cherry',    phonetic: '/ˈtʃeri/' },
    { emoji: '🫐', word: 'Blueberry', phonetic: '/ˈbluːberi/' },
    { emoji: '🍉', word: 'Watermelon',phonetic: '/ˈwɔːtəmelən/' },
  ],
  body: [
    { emoji: '👁️', word: 'Eye',       phonetic: '/aɪ/' },
    { emoji: '👂', word: 'Ear',       phonetic: '/ɪə/' },
    { emoji: '👃', word: 'Nose',      phonetic: '/noʊz/' },
    { emoji: '👄', word: 'Mouth',     phonetic: '/maʊθ/' },
    { emoji: '🦷', word: 'Tooth',     phonetic: '/tuːθ/' },
    { emoji: '💪', word: 'Arm',       phonetic: '/ɑːm/' },
    { emoji: '🦵', word: 'Leg',       phonetic: '/leɡ/' },
    { emoji: '🦶', word: 'Foot',      phonetic: '/fʊt/' },
    { emoji: '✋', word: 'Hand',      phonetic: '/hænd/' },
    { emoji: '🫀', word: 'Heart',     phonetic: '/hɑːt/' },
    { emoji: '🧠', word: 'Brain',     phonetic: '/breɪn/' },
    { emoji: '🦴', word: 'Bone',      phonetic: '/boʊn/' },
  ],
};

// Memory game card pool (emojis + labels)
const MEMORY_CARDS = [
  { emoji: '🦁', label: 'Lion'   },
  { emoji: '🐘', label: 'Elephant'},
  { emoji: '🐬', label: 'Dolphin'},
  { emoji: '🦋', label: 'Butterfly'},
  { emoji: '🐸', label: 'Frog'   },
  { emoji: '🦊', label: 'Fox'    },
  { emoji: '🐧', label: 'Penguin'},
  { emoji: '🐯', label: 'Tiger'  },
  { emoji: '🦒', label: 'Giraffe'},
  { emoji: '🐙', label: 'Octopus'},
  { emoji: '🦓', label: 'Zebra'  },
  { emoji: '🦜', label: 'Parrot' },
];

// Quiz questions pool
const QUIZ_QUESTIONS = [
  { emoji: '🐱', question: 'What animal is this?',     answer: 'Cat',    options: ['Dog', 'Cat', 'Fish', 'Bird'] },
  { emoji: '🍎', question: 'What fruit is this?',      answer: 'Apple',  options: ['Mango', 'Apple', 'Lemon', 'Peach'] },
  { emoji: '🔴', question: 'What color is this?',      answer: 'Red',    options: ['Blue', 'Green', 'Red', 'Yellow'] },
  { emoji: '🐘', question: 'What animal is this?',     answer: 'Elephant',options: ['Elephant', 'Horse', 'Rhino', 'Bear'] },
  { emoji: '🍌', question: 'What fruit is this?',      answer: 'Banana', options: ['Orange', 'Banana', 'Grapes', 'Lemon'] },
  { emoji: '🟡', question: 'What color is this?',      answer: 'Yellow', options: ['Yellow', 'Orange', 'Pink', 'Purple'] },
  { emoji: '🦁', question: 'What animal is this?',     answer: 'Lion',   options: ['Tiger', 'Cheetah', 'Lion', 'Leopard'] },
  { emoji: '🍓', question: 'What fruit is this?',      answer: 'Strawberry', options: ['Cherry', 'Strawberry', 'Raspberry', 'Apple'] },
  { emoji: '🔵', question: 'What color is this?',      answer: 'Blue',   options: ['Blue', 'Cyan', 'Purple', 'Green'] },
  { emoji: '🐸', question: 'What animal is this?',     answer: 'Frog',   options: ['Toad', 'Lizard', 'Frog', 'Turtle'] },
  { emoji: '🍇', question: 'What fruit is this?',      answer: 'Grapes', options: ['Grapes', 'Berries', 'Plums', 'Olives'] },
  { emoji: '🟢', question: 'What color is this?',      answer: 'Green',  options: ['Teal', 'Green', 'Lime', 'Yellow'] },
  { emoji: '🦋', question: 'What insect is this?',     answer: 'Butterfly',options:['Moth', 'Dragonfly', 'Butterfly', 'Bee'] },
  { emoji: '🍊', question: 'What fruit is this?',      answer: 'Orange', options: ['Peach', 'Mango', 'Orange', 'Apricot'] },
  { emoji: '🐶', question: 'What animal is this?',     answer: 'Dog',    options: ['Wolf', 'Dog', 'Fox', 'Bear'] },
];
